const superscript = {
   'A':'ᴬ',
   'B':'ᴮ',
   'C':'ᶜ',
   'D':'ᴰ',
   'E':'ᴱ',
   'F':'ᶠ',
   'G':'ᴳ',
   'H':'ᴴ',
   'I':'ᴵ',
   'J':'ᴶ',
   'K':'ᴷ',
   'L':'ᴸ',
   'M':'ᴹ',
   'N':'ᴺ',
   'O':'ᴼ',
   'P':'ᴾ',
   'Q':'ᑫ',
   'R':'ᴿ',
   'S':'ˢ',
   'T':'ᵀ',
   'U':'ᵁ',
   'V':'ⱽ',
   'W':'ᵂ',
   'X':'ˣ',
   'Y':'ʸ',
   'Z':'ᶻ',
   'a':'ᵃ',
   'b':'ᵇ',
   'c':'ᶜ',
   'd':'ᵈ',
   'e':'ᵉ',
   'f':'ᶠ',
   'g':'ᵍ',
   'h':'ʰ',
   'i':'ᶦ',
   'j':'ʲ',
   'k':'ᵏ', 
   'l':'ˡ',
   'm':'ᵐ',
   'n':'ⁿ',
   'o':'ᵒ',
   'p':'ᵖ',
   'q':'ᑫ',
   'r':'ʳ',
   's':'ˢ',
   't':'ᵗ',
   'u':'ᵘ',
   'v':'ᵛ',
   'w':'ʷ',
   'x':'ˣ',
   'y':'ʸ',
   'z':'ᶻ',
   '1':'¹',
   '2':'²',
   '3':'³',
   '4':'⁴',
   '5':'⁵',
   '6':'⁶',
   '7':'⁷',
   '8':'⁸',
   '9':'⁹',
   '0':'⁰',
}

const smallCaps = {
    'a':'ᴀ',
    'b':'ʙ',
    'c':'ᴄ',
    'd':'ᴅ',
    'e':'ᴇ',
    'f':'ғ',
    'g':'ɢ',
    'h':'ʜ',
    'i':'ɪ',
    'j':'ᴊ',
    'k':'ᴋ',
    'l':'ʟ',
    'm':'ᴍ',
    'n':'ɴ',
    'o':'ᴏ',
    'p':'ᴘ',
    'q':'ǫ',
    'r':'ʀ',
    's':'s',
    't':'ᴛ',
    'u':'ᴜ',
    'v':'ᴠ',
    'w':'ᴡ',
    'x':'x',
    'y':'ʏ',
    'z':'ᴢ'
}

const strikeThrough = {
    'A':' ̶A̶',
    'B':' ̶B̶',
    'C':' ̶C̶',
    'D':' ̶D̶',
    'E':' ̶E̶',
    'F':' ̶F̶',
    'G':' ̶G̶',
    'H':' ̶H̶',
    'I':' ̶I̶',
    'J':' ̶J̶',
    'K':' ̶K̶',
    'L':' ̶L̶',
    'M':' ̶M̶',
    'N':' ̶N̶',
    'O':' ̶O̶',
    'P':' ̶P̶',
    'Q':' ̶Q̶',
    'R':' ̶R̶',
    'S':' ̶S̶',
    'T':' ̶T̶',
    'U':' ̶U̶',
    'V':' ̶V̶',
    'W':' ̶W̶',
    'X':' ̶X̶',
    'Y':' ̶Y̶',
    'Z':' ̶Z̶',
    'a':' ̶a̶',
    'b':' ̶b̶',
    'c':' ̶c̶',
    'd':'d̶',
    'e':' ̶e̶',
    'f':' ̶f̶',
    'g':' ̶g̶',
    'h':' ̶h̶',
    'i':' ̶i̶',
    'j':' ̶j̶',
    'k':' ̶k̶',
    'l':' ̶l̶',
    'm':' ̶m̶',
    'n':' ̶n̶',
    'o':' ̶o̶',
    'p':' ̶p̶',
    'q':' ̶q̶',
    'r':' ̶r̶',
    's':' ̶s̶',
    't':' ̶t̶',
    'u':' ̶u̶',
    'v':' ̶v̶',
    'w':' ̶w̶',
    'x':' ̶x̶',
    'y':' ̶y̶',
    'z':' ̶z̶',
    '1':' ̶1̶',
    '2':' ̶2̶',
    '3':' ̶3̶',
    '4':' ̶4̶',
    '5':' ̶5̶',
    '6':' ̶6̶',
    '7':' ̶7̶',
    '8':' ̶8̶',
    '9':' ̶9̶',
    '0':' ̶0̶',
    '!':' ̶!̶',
    '?':' ̶?̶'
}

const startText = `
Hey I'm BarkupBot! I'm an easy way to create stylized text in telegram!
Here are the commands you can access from here, but you can message me directly in any chat and get the exact same features!
/bold Make your text bold
/italics Make your text italicized
/tiny Make your text ᵗᶦⁿʸ
/smallcaps Make your text sᴍᴀʟʟ ᴡɪᴛʜ ᴄᴀᴘs
/strthr Make your text  ̶c̶r̶o̶s̶s̶e̶d̶ ̶o̶u̶t̶
`;

module.exports = {
    superscript,
    smallCaps,
    strikeThrough,
    startText
}