const superscript = {
   'A':'ᴬ',
   'B':'ᴮ',
   'C':'ᶜ',
   'D':'ᴰ',
   'E':'ᴱ',
   'F':'ᶠ',
   'G':'ᴳ',
   'H':'ᴴ',
   'I':'ᴵ',
   'J':'ᴶ',
   'K':'ᴷ',
   'L':'ᴸ',
   'M':'ᴹ',
   'N':'ᴺ',
   'O':'ᴼ',
   'P':'ᴾ',
   'Q':'ᑫ',
   'R':'ᴿ',
   'S':'ˢ',
   'T':'ᵀ',
   'U':'ᵁ',
   'V':'ⱽ',
   'W':'ᵂ',
   'X':'ˣ',
   'Y':'ʸ',
   'Z':'ᶻ',
   'a':'ᵃ',
   'b':'ᵇ',
   'c':'ᶜ',
   'd':'ᵈ',
   'e':'ᵉ',
   'f':'ᶠ',
   'g':'ᵍ',
   'h':'ʰ',
   'i':'ᶦ',
   'j':'ʲ',
   'k':'ᵏ', 
   'l':'ˡ',
   'm':'ᵐ',
   'n':'ⁿ',
   'o':'ᵒ',
   'p':'ᵖ',
   'q':'ᑫ',
   'r':'ʳ',
   's':'ˢ',
   't':'ᵗ',
   'u':'ᵘ',
   'v':'ᵛ',
   'w':'ʷ',
   'x':'ˣ',
   'y':'ʸ',
   'z':'ᶻ',
   '1':'¹',
   '2':'²',
   '3':'³',
   '4':'⁴',
   '5':'⁵',
   '6':'⁶',
   '7':'⁷',
   '8':'⁸',
   '9':'⁹',
   '0':'⁰',
}

const smallCaps = {
    'a':'ᴀ',
    'b':'ʙ',
    'c':'ᴄ',
    'd':'ᴅ',
    'e':'ᴇ',
    'f':'ғ',
    'g':'ɢ',
    'h':'ʜ',
    'i':'ɪ',
    'j':'ᴊ',
    'k':'ᴋ',
    'l':'ʟ',
    'm':'ᴍ',
    'n':'ɴ',
    'o':'ᴏ',
    'p':'ᴘ',
    'q':'ǫ',
    'r':'ʀ',
    's':'s',
    't':'ᴛ',
    'u':'ᴜ',
    'v':'ᴠ',
    'w':'ᴡ',
    'x':'x',
    'y':'ʏ',
    'z':'ᴢ'
}

const strikeThrough = {
    'A':' ̶A̶',
    'B':' ̶B̶',
    'C':' ̶C̶',
    'D':' ̶D̶',
    'E':' ̶E̶',
    'F':' ̶F̶',
    'G':' ̶G̶',
    'H':' ̶H̶',
    'I':' ̶I̶',
    'J':' ̶J̶',
    'K':' ̶K̶',
    'L':' ̶L̶',
    'M':' ̶M̶',
    'N':' ̶N̶',
    'O':' ̶O̶',
    'P':' ̶P̶',
    'Q':' ̶Q̶',
    'R':' ̶R̶',
    'S':' ̶S̶',
    'T':' ̶T̶',
    'U':' ̶U̶',
    'V':' ̶V̶',
    'W':' ̶W̶',
    'X':' ̶X̶',
    'Y':' ̶Y̶',
    'Z':' ̶Z̶',
    'a':' ̶a̶',
    'b':' ̶b̶',
    'c':' ̶c̶',
    'd':' ̶d̶',
    'e':' ̶e̶',
    'f':' ̶f̶',
    'g':' ̶g̶',
    'h':' ̶h̶',
    'i':' ̶i̶',
    'j':' ̶j̶',
    'k':' ̶k̶',
    'l':' ̶l̶',
    'm':' ̶m̶',
    'n':' ̶n̶',
    'o':' ̶o̶',
    'p':' ̶p̶',
    'q':' ̶q̶',
    'r':' ̶r̶',
    's':' ̶s̶',
    't':' ̶t̶',
    'u':' ̶u̶',
    'v':' ̶v̶',
    'w':' ̶w̶',
    'x':' ̶x̶',
    'y':' ̶y̶',
    'z':' ̶z̶',
    '1':' ̶1̶',
    '2':' ̶2̶',
    '3':' ̶3̶',
    '4':' ̶4̶',
    '5':' ̶5̶',
    '6':' ̶6̶',
    '7':' ̶7̶',
    '8':' ̶8̶',
    '9':' ̶9̶',
    '0':' ̶0̶',
    '!':' ̶!̶',
    '?':' ̶?̶'
}

const fullWidth = {
    'A':'Ａ',
    'B':'Ｂ',
    'C':'Ｃ',
    'D':'Ｄ',
    'E':'Ｅ',
    'F':'Ｆ',
    'G':'Ｇ',
    'H':'Ｈ',
    'I':'Ｉ',
    'J':'Ｊ',
    'K':'Ｋ',
    'L':'Ｌ',
    'M':'Ｍ',
    'N':'Ｎ',
    'O':'Ｏ',
    'P':'Ｐ',
    'Q':'Ｑ',
    'R':'Ｒ',
    'S':'Ｓ',
    'T':'Ｔ',
    'U':'Ｕ',
    'V':'Ｖ',
    'W':'Ｗ',
    'X':'Ｘ',
    'Y':'Ｙ',
    'Z':'Ｚ',
    'a':'ａ',
    'b':'ｂ',
    'c':'ｃ',
    'd':'ｄ',
    'e':'ｅ',
    'f':'ｆ',
    'g':'ｇ',
    'h':'ｈ',
    'i':'ｉ',
    'j':'ｊ',
    'k':'ｋ',
    'l':'ｌ',
    'm':'ｍ',
    'n':'ｎ',
    'o':'ｏ',
    'p':'ｐ',
    'q':'ｑ',
    'r':'ｒ',
    't':'ｔ',
    'u':'ｕ',
    'v':'ｖ',
    'w':'ｗ',
    'x':'ｘ',
    'y':'ｙ',
    'z':'ｚ',
    '0':'０',
    '1':'１',
    '2':'２',
    '3':'３',
    '4':'４',
    '5':'５',
    '6':'６',
    '7':'７',
    '8':'８',
    '9':'９' 
}

const underLine = {
    'A':'A̲',
    'B':'B̲',
    'C':'C̲',
    'D':'D̲',
    'E':'E̲',
    'F':'F̲',
    'G':'G̲',
    'H':'H̲',
    'I': ' I̲',
    'J':'J̲',
    'K':'K̲',
    'L':'L̲',
    'M':'M̲',
    'N':'N̲',
    'O':'O̲',
    'P':'P̲',
    'Q':'Q̲',
    'R':'R̲',
    'S':'S̲',
    'U':'U̲',
    'V':'V̲',
    'W':'W̲',
    'X':'X̲',
    'Y':'Y̲',
    'Z':'Z̲',
    'a':'a̲',
    'b':'b̲',
    'c':'c̲',
    'd':'d̲',
    'e':'e̲',
    'f':'f̲',
    'g':'g̲',
    'h':'h̲',
    'i':'i̲',
    'j':'j̲',
    'k':'k̲',
    'l':'l̲',
    'm':'m̲',
    'n':'n̲',
    'o':'o̲',
    'p':'p̲',
    'q':'q̲',
    'r':'r̲',
    's':'s̲',
    't':'t̲',
    'u':'u̲',
    'v':'v̲',
    'w':'w̲',
    'x':'x̲',
    'y':'y̲',
    'z':'z̲',
    '0':'0̲',
    '1':'1̲',
    '2':'2̲',
    '3':'3̲',
    '4':'4̲',
    '5':'5̲',
    '6':'6̲',
    '7':'7̲',
    '8':'8̲',
    '9':' 9̲',
    '?':'?̲',
    '!':'!̲',
    '\'':'\'̲',
    '\"':'\"̲'

}

const startText = `
Hey I'm BarkupBot! I'm an easy way to create stylized text in Telegram!
Here are the commands you can access from here, but you can message me directly in any chat and get the exact same features!
/bold Make your text bold
/italics Make your text italicized
/tiny Make your text ᵗᶦⁿʸ
/smallcaps Make your text sᴍᴀʟʟ ᴡɪᴛʜ ᴄᴀᴘs
/strthr Make your text  ̶c̶r̶o̶s̶s̶e̶d̶ ̶o̶u̶t̶
/under Make your text  u̲n̲d̲e̲r̲l̲i̲n̲e̲d̲
/full Make you text ａｅｓｔｈｅｔｉｃ 
/mock Make your text mOcKiNg
/custom Granular control of how your messages appear with letter by letter control of their formatting
/customhelp Guide on how to take advantage of the custom command
`;

const customHelpText = `
BarkupBot uses tags to help filter out what text you'd like to modify. Simply place whatever text you'd like modified between these tags and BarkupBot will take care of the rest.
Tags are made of two parentheses with a single character in the middle to specify what formatting should be used. 

Each formatting option has its own tag, here are the available tags:

\`/custom (b) Bold text (b)\` 🡺 *Bold text*
\`/custom (i) Italicized text (i)\` 🡺 _Italicized text_
\`/custom (t) tiny text (t)\` 🡺 ᵗᶦⁿʸ ᵗᵉˣᵗ
\`/custom (s) small caps (s)\` 🡺 sᴍᴀʟʟ ᴄᴀᴘs
\`/custom (-) strike through (-)\` 🡺 ̶s̶̶t̶̶r̶̶i̶̶k̶̶e̶ ̶t̶̶h̶̶r̶̶o̶̶u̶̶g̶h̶
\`/custom (u) underline (u)\` 🡺  u̲n̲d̲e̲r̲l̲i̲n̲e̲d̲
\`/custom (f) full width (f)\` 🡺  ａｅsｔｈｅｔｉｃ
\`/custom (m) mock (m)\` 🡺 mOcK

With this tool you can mix formatting types and output them in one message!

Example: 
'Barkup Bot is (-)a great(-) the (b)best(b) way to (i)format(i) text!'
Outputs:
Barkup Bot is  ̶a ̶g̶r̶e̶a̶t  the *best* way to _format_ text!

`

module.exports = {
    superscript,
    smallCaps,
    strikeThrough,
    fullWidth,
    underLine,
    startText,
    customHelpText
}