const superscript = {
   'A':'ᴬ',
   'B':'ᴮ',
   'C':'ᶜ',
   'D':'ᴰ',
   'E':'ᴱ',
   'F':'ᶠ',
   'G':'ᴳ',
   'H':'ᴴ',
   'I':'ᴵ',
   'J':'ᴶ',
   'K':'ᴷ',
   'L':'ᴸ',
   'M':'ᴹ',
   'N':'ᴺ',
   'O':'ᴼ',
   'P':'ᴾ',
   'Q':'ᑫ',
   'R':'ᴿ',
   'S':'ˢ',
   'T':'ᵀ',
   'U':'ᵁ',
   'V':'ⱽ',
   'W':'ᵂ',
   'X':'ˣ',
   'Y':'ʸ',
   'Z':'ᶻ',
   'a':'ᵃ',
   'b':'ᵇ',
   'c':'ᶜ',
   'd':'ᵈ',
   'e':'ᵉ',
   'f':'ᶠ',
   'g':'ᵍ',
   'h':'ʰ',
   'i':'ᶦ',
   'j':'ʲ',
   'k':'ᵏ', 
   'l':'ˡ',
   'm':'ᵐ',
   'n':'ⁿ',
   'o':'ᵒ',
   'p':'ᵖ',
   'q':'ᑫ',
   'r':'ʳ',
   's':'ˢ',
   't':'ᵗ',
   'u':'ᵘ',
   'v':'ᵛ',
   'w':'ʷ',
   'x':'ˣ',
   'y':'ʸ',
   'z':'ᶻ',
   '1':'¹',
   '2':'²',
   '3':'³',
   '4':'⁴',
   '5':'⁵',
   '6':'⁶',
   '7':'⁷',
   '8':'⁸',
   '9':'⁹',
   '0':'⁰',
}

const smallCaps = {
    'a':'ᴀ',
    'b':'ʙ',
    'c':'ᴄ',
    'd':'ᴅ',
    'e':'ᴇ',
    'f':'ғ',
    'g':'ɢ',
    'h':'ʜ',
    'i':'ɪ',
    'j':'ᴊ',
    'k':'ᴋ',
    'l':'ʟ',
    'm':'ᴍ',
    'n':'ɴ',
    'o':'ᴏ',
    'p':'ᴘ',
    'q':'ǫ',
    'r':'ʀ',
    's':'s',
    't':'ᴛ',
    'u':'ᴜ',
    'v':'ᴠ',
    'w':'ᴡ',
    'x':'x',
    'y':'ʏ',
    'z':'ᴢ'
}

const startText = `
Hey I'm BarkupBot! I'm an easy way to create stylized text in telegram!
Here are the commands you can access from here, but you can message me directly in any chat and get the exact same features!
/bold Make your text bold
/italics Make your text italicized
`;

module.exports = {
    superscript,
    smallCaps,
    startText
}